openapi: 3.0.0
info:
  title: Paper Analysis System API
  description: API interface for paper search, analysis and clustering functionality
  version: 1.0.0
  contact:
    email: support@example.com

servers:
  - url: http://localhost:5000
    description: Local Development Server

paths:
  /search:
    get:
      summary: Local Paper Search
      description: Search papers in local database
      parameters:
        - name: type
          in: query
          description: Entity type
          required: true
          schema:
            type: string
            enum: [person, organisation, work]
        - name: name
          in: query
          description: Entity name
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: Result limit
          required: false
          schema:
            type: string
            enum: [all, one]
      responses:
        '200':
          description: Search successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  papers:
                    type: array
                    items:
                      $ref: '#/components/schemas/Paper'
        '400':
          description: Invalid request parameters
        '500':
          description: Server error

  /arxiv/search:
    get:
      summary: arXiv Paper Search
      description: Search papers in arXiv library
      parameters:
        - name: query
          in: query
          description: Search keywords
          required: true
          schema:
            type: string
        - name: max_results
          in: query
          description: Maximum number of results
          required: false
          schema:
            type: integer
            default: 10
        - name: cluster
          in: query
          description: Whether to perform clustering
          required: false
          schema:
            type: boolean
            default: false
        - name: n_clusters
          in: query
          description: Number of clusters
          required: false
          schema:
            type: integer
            default: 5
      responses:
        '200':
          description: Search successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  papers:
                    type: array
                    items:
                      $ref: '#/components/schemas/ArxivPaper'
                  clusters:
                    $ref: '#/components/schemas/Clusters'
        '400':
          description: Invalid request parameters
        '500':
          description: Server error

  /analyze/sentiment:
    post:
      summary: Paper Sentiment Analysis
      description: Analyze sentiment of paper text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paper_id:
                  type: integer
                text:
                  type: string
      responses:
        '200':
          description: Analysis successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SentimentResult'
        '400':
          description: Invalid request parameters
        '500':
          description: Server error

  /papers/{paper_id}/sentiment:
    get:
      summary: Get Paper Sentiment Analysis Result
      description: Get sentiment analysis result for specified paper
      parameters:
        - name: paper_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Retrieval successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SentimentResult'
        '404':
          description: Paper not found
        '500':
          description: Server error

  /arxiv/metadata/analysis:
    get:
      summary: arXiv Metadata Analysis
      description: Analyze arXiv paper metadata
      parameters:
        - name: limit
          in: query
          description: Amount of data to analyze
          required: false
          schema:
            type: integer
            default: 1000
      responses:
        '200':
          description: Analysis successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataAnalysis'
        '500':
          description: Server error

components:
  schemas:
    Paper:
      type: object
      properties:
        paper_id:
          type: integer
        title:
          type: string
        abstract:
          type: string
        entity_type:
          type: string
        entity_name:
          type: string

    ArxivPaper:
      type: object
      properties:
        arxiv_id:
          type: string
        title:
          type: string
        abstract:
          type: string
        authors:
          type: array
          items:
            type: string
        categories:
          type: array
          items:
            type: string
        published:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
        pdf_url:
          type: string

    Clusters:
      type: object
      properties:
        clusters:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              properties:
                paper_id:
                  type: string
                title:
                  type: string
                x:
                  type: number
                y:
                  type: number
        cluster_terms:
          type: object
          additionalProperties:
            type: array
            items:
              type: string

    SentimentResult:
      type: object
      properties:
        status:
          type: string
        results:
          type: object
          properties:
            overall_sentiment:
              type: object
              properties:
                polarity:
                  type: number
                subjectivity:
                  type: number
            sentiment_label:
              type: string
            sentence_sentiments:
              type: array
              items:
                type: object
                properties:
                  text:
                    type: string
                  polarity:
                    type: number
                  subjectivity:
                    type: number

    MetadataAnalysis:
      type: object
      properties:
        status:
          type: string
        analysis_results:
          type: object
          properties:
            basic_stats:
              type: object
              properties:
                total_papers:
                  type: integer
                papers_with_doi:
                  type: integer
                papers_with_license:
                  type: integer
                papers_with_journal_ref:
                  type: integer
            category_analysis:
              type: object
              properties:
                category_distribution:
                  type: object
                  additionalProperties:
                    type: integer
            time_analysis:
              type: object
              properties:
                yearly_distribution:
                  type: object
                  additionalProperties:
                    type: integer
                version_distribution:
                  type: object
                  additionalProperties:
                    type: integer
            author_analysis:
              type: object
              properties:
                top_authors:
                  type: object
                  additionalProperties:
                    type: integer 